name: demo-project
kind: Project
backend: gcs-backend
variables:
  organization: my-organization
  project: cdev-demo
  domain: gcp.cluster.dev
  environment: demo
  region: us-west1
  state_bucket_name: gke-demo-state
  state_bucket_prefix: demo
